Creating Client Service
rodolfoperatello/bicycle-shop-backend pull request #11
Opened 2020-09-16 19:50 UTC by rodolfoperatello

Creating client service with Client and Adress repository

2020-09-18 01:31 UTC, alexandre-exacta requested changes

2020-09-18 01:31 UTC, alexandre-exacta commented on src/main/java/br/com/exactalabs/bicycleshop/entity/Adress.java
> +    @NotBlank(message = "A rua não pode ser vazio")
NotBlank já valida para valores nulos também. Então usar NotNull e NotBlank juntos é ambiguo

2020-09-18 01:31 UTC, alexandre-exacta commented on src/main/java/br/com/exactalabs/bicycleshop/entity/Client.java
> +    @NotBlank(message = "O nome não pode ser vazio")
NotBlank duplicado

2020-09-18 01:31 UTC, alexandre-exacta commented on src/main/java/br/com/exactalabs/bicycleshop/entity/Client.java
> +    @NotBlank(message = "O sobrenome não pode ser vazio")
Mesmo caso de abiguidade de NotNull e NotBlank

2020-09-18 01:31 UTC, alexandre-exacta commented on src/main/java/br/com/exactalabs/bicycleshop/entity/Client.java
> +    @NotNull(message = "O endereço do cliente não pode ser nulo")
Uma lista nula é o mesmo que uma lista vazia?

2020-09-18 01:31 UTC, alexandre-exacta commented on src/main/java/br/com/exactalabs/bicycleshop/service/ClientService.java
> +    public void deleteClientById(Long id) {
Porque não usar o cascade delete de endereços no mapeamento para facilitar a vida?

2020-09-23 18:48 UTC, gilsonexacta requested changes

2020-09-23 18:48 UTC, gilsonexacta commented on src/main/java/br/com/exactalabs/bicycleshop/entity/Client.java
> +    private Collection<@NotNull(message = "O endereço não pode ser nulo") Adress> adressList = new ArrayList<>();
@NotNull deveria estar separado.

2020-09-23 23:25 UTC, rodolfoperatello commented on src/main/java/br/com/exactalabs/bicycleshop/entity/Client.java
> +    private Collection<@NotNull(message = "O endereço não pode ser nulo") Adress> adressList = new ArrayList<>();
@gilsonexacta Eu pensei em colocar o @NotNull em cima do atributo adressList, mas não fiz isso porque como eu já instancio o adressList automaticamente no atributo, então não teria como essa lista ser nulo. Entretanto, eu queria evitar que fosse possível adicionar um endereço nulo dentro da lista e essa foi a única maneira que eu consegui, tentei colocar @NotNull no método addAdress mas mesmo assim acaba possibilitando a inserção de um endereço nulo no banco de dados e não sabia se era por causa do cascade.type ALL que estava permitindo fazer isso

2020-09-24 11:52 UTC, gilsonexacta commented on src/main/java/br/com/exactalabs/bicycleshop/entity/Client.java
> +    private Collection<@NotNull(message = "O endereço não pode ser nulo") Adress> adressList = new ArrayList<>();
Você tentou colocar o @Valid na Collection?

2020-09-24 14:49 UTC, alexandre-exacta commented on src/main/java/br/com/exactalabs/bicycleshop/entity/Client.java
> +    private Collection<@NotNull(message = "O endereço não pode ser nulo") Adress> adressList = new ArrayList<>();
Usar @NotEmpty como haviamos conversado não funcionou?

2020-09-24 19:07 UTC, rodolfoperatello commented on src/main/java/br/com/exactalabs/bicycleshop/entity/Client.java
> +    private Collection<@NotNull(message = "O endereço não pode ser nulo") Adress> adressList = new ArrayList<>();
@alexandre-exacta @gilsonexacta Testei as duas abordagens mas ainda foi possível inserir um endereço nulo no banco de dados. Existe alguma outra possibilidade para resolver esse problema?

2020-09-24 20:29 UTC, closed without merging