Feature/ls 162
rodolfoperatello/bicycle-shop-backend pull request #12
Opened 2020-09-21 00:57 UTC by rodolfoperatello

Creating Product Service

2020-09-23 18:43 UTC, gilsonexacta requested changes
Remova o código comentado caso ele realmente não seja necessário.

2020-09-23 18:43 UTC, gilsonexacta commented on src/main/java/br/com/exactalabs/bicycleshop/repository/ProductRepository.java
> +    Page<Product> findAllProductByOrderByPriceDesc(Pageable pageRequest);
Dúvida. Estes 2 métodos funcionam sem passar parâmetros? Não deveria ser passado o orderPrice?

2020-09-23 23:18 UTC, rodolfoperatello commented on src/main/java/br/com/exactalabs/bicycleshop/repository/ProductRepository.java
> +    Page<Product> findAllProductByOrderByPriceDesc(Pageable pageRequest);
Esses dois métodos conseguem fazer a classificação de preço, seja ASC ou DESC, automaticamente, sem a necessidade de passar um parâmetro. Eu criei esse método pensando no filtro de preço que existe no front-end, onde será possível organizar os produtos na tela com base no menor ou maior preço.

2020-09-24 11:51 UTC, gilsonexacta approved these changes

2020-09-24 19:33 UTC, merged