Feature/ls 164
rodolfoperatello/bicycle-shop-backend pull request #13
Opened 2020-09-21 16:48 UTC by rodolfoperatello

Creating BankSlip ORM

2020-09-23 18:40 UTC, gilsonexacta requested changes

2020-09-23 18:40 UTC, gilsonexacta commented on src/main/java/br/com/exactalabs/bicycleshop/entity/BankSlip.java
> +    private String number;
Faz sentido os nomes no banco serem diferentes do código java?

2020-09-28 13:34 UTC, gilsonexacta approved these changes

2020-09-29 11:39 UTC, alexandre-exacta approved these changes

2020-09-29 12:41 UTC, merged