Feature/ls 166
rodolfoperatello/bicycle-shop-backend pull request #14
Opened 2020-09-21 16:53 UTC by rodolfoperatello

Creating CreditCard ORM

2020-09-23 18:38 UTC, gilsonexacta requested changes

2020-09-23 18:38 UTC, gilsonexacta commented on src/main/java/br/com/exactalabs/bicycleshop/entity/CreditCard.java
> +    private String number;
Faz sentido a coluna na tabela ter um nome diferente?

2020-09-28 13:32 UTC, gilsonexacta approved these changes

2020-09-29 11:40 UTC, alexandre-exacta approved these changes

2020-09-29 12:42 UTC, merged