Feature/ls 160
rodolfoperatello/bicycle-shop-backend pull request #15
Opened 2020-09-24 20:39 UTC by rodolfoperatello

Creating new Client Service

2020-09-28 13:30 UTC, gilsonexacta requested changes

2020-09-28 13:30 UTC, gilsonexacta commented on src/main/java/br/com/exactalabs/bicycleshop/repository/AddressRepository.java
> +}
Acho que não tem necessidade desta classe.

2020-09-28 13:33 UTC, rodolfoperatello commented on src/main/java/br/com/exactalabs/bicycleshop/repository/AddressRepository.java
> +}
@gilsonexacta Concordo, ela não está nem sendo usado na CustomerService, irei fazer a remoção

2020-09-28 13:38 UTC, gilsonexacta approved these changes

2020-09-29 11:41 UTC, alexandre-exacta approved these changes

2020-09-29 12:17 UTC, merged