Feature/ls 151
rodolfoperatello/bicycle-shop-backend pull request #20
Opened 2020-09-30 13:03 UTC by rodolfoperatello

Creating OrderService and update in Payment inheritance

2020-09-30 13:35 UTC, gilsonexacta requested changes

2020-09-30 13:35 UTC, gilsonexacta commented on src/main/java/br/com/exactalabs/bicycleshop/entity/OrderedItem.java
> +@Table(name = "orderedItems")
a entidade não deveria ser snake case?
Outro detalhe, não ficaria melhor chamar apenas de order_items e a outra entidade order?

2020-09-30 13:54 UTC, rodolfoperatello commented on src/main/java/br/com/exactalabs/bicycleshop/entity/OrderedItem.java
> +@Table(name = "orderedItems")
@gilsonexacta Realmente renomear a entidade para order_items e order seria melhor. Não estou usando snake case no nome das tabelas, apenas nos atributos. Também é padrão utilizar snake case no nome da tabela?

2020-09-30 14:05 UTC, gilsonexacta commented on src/main/java/br/com/exactalabs/bicycleshop/entity/OrderedItem.java
> +@Table(name = "orderedItems")
@rodolfoperatello sim!!

2020-09-30 18:55 UTC, rodolfoperatello commented on src/main/java/br/com/exactalabs/bicycleshop/entity/OrderedItem.java
> +@Table(name = "orderedItems")
@gilsonexacta No java eu deixei a classe de itens do pedido com o nome de OrderItems, mas não seria melhor ela se chamar OrderItem, sendo que ela é a representação de um único item do pedido e não de vários?

2020-10-01 15:05 UTC, gilsonexacta requested changes

2020-10-01 15:05 UTC, gilsonexacta commented on src/main/java/br/com/exactalabs/bicycleshop/entity/OrderItem.java
> +    private int quantitaty;
o correto não seria quantity?

2020-10-01 15:16 UTC, gilsonexacta approved these changes

2020-10-02 12:51 UTC, merged