Feature/ls 189
rodolfoperatello/bicycle-shop-backend pull request #24
Opened 2020-10-13 14:38 UTC by rodolfoperatello

Creating Endpoints in ProductController;
Removing productList attribute in ProductCategory class;
Inserting new attributes in Address class;
Creating Builder in Customer and Address class.

2020-10-13 15:06 UTC, gilsonexacta requested changes
Veja se faz sentido os comentáqrios antes de alterar o código ok?

2020-10-13 15:06 UTC, gilsonexacta commented on build.gradle
> +0
O que é este "0"??

2020-10-13 15:06 UTC, gilsonexacta commented on src/main/java/br/com/exactalabs/bicycleshop/controller/ProductController.java
> +    public ResponseEntity<?> findProductById(@RequestParam Long id){
Não seria mais interessnate passar o parametro por PathVariable?

2020-10-13 15:06 UTC, gilsonexacta commented on src/main/java/br/com/exactalabs/bicycleshop/controller/ProductController.java
> +    public ResponseEntity<?> findProductByName(
Não seria mais interessnate passar o parametro por PathVariable?

2020-10-13 15:06 UTC, gilsonexacta commented on src/main/java/br/com/exactalabs/bicycleshop/controller/ProductController.java
> +    public ResponseEntity<?> updateProduct(@RequestParam Long id, @RequestBody Product product){
Não seria mais interessnate passar o parametro por PathVariable?

2020-10-13 16:43 UTC, rodolfoperatello commented on src/main/java/br/com/exactalabs/bicycleshop/controller/ProductController.java
> +    public ResponseEntity<?> findProductById(@RequestParam Long id){
Realmente eu não sei qual seria a melhor abordagem, se é passar por PathVariable ou RequestParam

2020-10-13 16:44 UTC, rodolfoperatello commented on build.gradle
> +0
Acredito que eu tenha aperto o 0 do teclado sem querer e na hora de enviar o commit o arquivo tenha subido junto

2020-10-13 18:59 UTC, darnosls commented on src/main/java/br/com/exactalabs/bicycleshop/controller/ProductController.java
> +    public ResponseEntity<?> findProductById(@RequestParam Long id){
@rodolfoperatello , nesse caso eu sugiro utilizar o PathVariable, para manter a ideia de _Uniform Interface_.
Você pode fazer algo similar a isso: @GetMapping(value = "/{id}") pra poder recuperar o valor que identifica o recurso que está sendo feito o GET. Dessa forma você estabelece um padrão para quando esse _endpoint_ for consumido pelo _client_, caso ele passe qualquer coisa diferente do uuid ele receberá um status na casa do 400

2020-10-13 19:00 UTC, darnosls commented on src/main/java/br/com/exactalabs/bicycleshop/controller/ProductController.java
> +    public ResponseEntity<?> findProductByName(
Aqui além do PathVariable, se for mesmo necessário recuperar um recurso pelo nome, seria mais interessante adicionar mais uma cama da na URI
ex: /product/name/{name}, e da mesma forma que o endpoint anterior, você recupera o valor `{name}` com o `PathVariable`

2020-10-13 19:18 UTC, darnosls reviewed
Adicionei alguns comentários, e também senti falta do endpoint de cancelamento.

2020-10-14 13:29 UTC, rodolfoperatello commented
> Adicionei alguns comentários, e também senti falta do endpoint de cancelamento.

Conforme conversa com Gilson, no escopo do projeto do BicycleShop não existe uma tela de admin responsável por gerenciar os produtos. Sendo assim, o endpoint para deletar produtos não será implementado no momento.

2020-10-14 18:48 UTC, darnosls approved these changes
Sei que a gente já falou sobre o motivo de não ter os links na representação dos produtos, mas deixo como sugestão caso venha ter uma melhoria no futuro.

Lembrando que a idéia de adicionar os links vem do padrão **HATEOAS** (_Hypermedia as the Engine of Application State_), que é um dos principais componente do REST.
Ao aplicar esse padrão a comunicação entre o cliente e a API fica mais dinâmica, uma vez que o cliente não precisa saber de todos os endpoints disponíveis na API, a medida que a api fornece a representação de um recurso ela disponibiliza os possiveis endpoints que o cliente poderá explorar.

Veja um exemplo:

```
{
    "id": 1,
    "name": "smartphone xpto",
    "price": 1000.00,
    "productCategory": {
        "id": 1,
        "name": "eletrônicos"
    },
    "links": [
    	{
        	"method": "GET",
        	"rel": "getProductById"
        	"href": "http://localhost:8080/api/product/1"
        }
        {
        	"method": "GET",
        	"rel": "listProducs"
        	"href": "http://localhost:8080/api/product"
        }
    ]
}
```

Observe que dentro do nó _links_ a API fornece ao cliente as informações necessária pra a manipulação de um determinado recurso.

2020-10-15 12:37 UTC, gilsonexacta approved these changes

2020-10-15 12:48 UTC, merged